### PR TITLE
11 serialization update

### PR DESCRIPTION
**Pull request by cmota**
- updated all libraries to the latest versions
- no longer need to have pager/pager-indicators library (they are now available for the latest version of compose)
- kamel library is now included in the project due to the latest changes on ktor (version 2.0.0-beta-1)
- used swift lint (from RW) and fixed all the warnings
- minor improvements
- code reformat

### CODE REVIEW

**Comment by cmota** [comment]
@SubhrajyotiSen this one is ready for acceptance 🙂

**Review by SubhrajyotiSen — DISMISSED** [review]

**Review by SubhrajyotiSen — DISMISSED** [review]

**Comment by cmota** [comment]
I've made a couple more updates on this one:
- Remove the Pods folder (it's not necessary on iOS)
- Updated the Podfile with more information about the build to avoid a warning on Xcode
- Updated the desktop BundleId to be consistent with Android and iOS 

You can accept this one from my side - thank you 🙂

**Comment by SubhrajyotiSen** [comment]
@cmota I am unable to build the starter iOS project from this branch. Can you please take a look once?
The final project builds fine

**Comment by cmota** [comment]
hello @SubhrajyotiSen, which error are you getting?

I've just checked out the project, run the `pod install` and compiled the app successfully. 

I've made a push earlier today where I've removed the Pods, if you've updated from that branch you might need to go to "Product" > "Clean Build Folder" before.

**Review by SubhrajyotiSen — APPROVED** [review]

**Comment by SubhrajyotiSen** [comment]
@cmota Cleaning the build folder fixed the issue for me. Thanks :]

**Pull request merged**
